### PR TITLE
Feature/lerna

### PR DESCRIPTION
**Pull request by guilhermelimak**
This PR will make the `perry-js/perry` repository a lerna monorepo and the perry client that was in this repo will be moved to the `perry-client` package.

### CODE REVIEW

**Comment by armand1m** [comment]
Hey, I'll try to give this some attention soon, I want to get this merged but I wish we kept the deployment working. Maybe it is good to make some work in netlify to deploy this branch?

**Comment by jackTheRipper** [comment]
What do you think about using Lerna + Yarn workspace here?

**Comment by armand1m** [comment]
I think we can do it of course =)

**Comment by armand1m** [comment]
But I do think that we should start out by using lerna only at a first step, then we see if yarn integration would be helpful.

I am quite afraid of locking vendor myself to yarn due to the workspace implementation, lerna seems more adaptable  to the future at a first step. I also lack the knowledge on yarn workspaces tbh, so maybe a separate pull request for each would make it easier to understand it

**Comment by armand1m** [comment]
we just merged #66 which was a whole rearchitecture of perry on lerna and yarn workspaces

check it out later =)

**Pull request closed without merging**
